### ISSUE TITLE
Unable to execute program, code's fault?

### ISSUE THREAD

**Issue by Novantric** [dslul/logiconf#3]
Heyo,
Just purchased the same mouse you mentioned you tested this code on.
I tried assembling the code as instructed and i am returned with:
*Note that the binary from the releases tab has been renamed to `run` and is in the ~/logiconf folder

`$ sudo ./run`
`QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'`
`/dev/hidraw1`
`angle_snapping`
`color`
`default_dpi`
`name`
`report_rate`
`revision`
`switched_dpi`
`/home/novastorm64/.cache/run/settings.json`
`terminate called after throwing an instance of 'std::out_of_range'`
`  what():  map::at`
`Aborted`
Can you help me get it working? A blank GUI window pops up for a millisecond when this code is executed.

**Comment by dslul** [comment]
Hi, can you try with the original file name?

**Comment by Novantric** [comment]
No change. Tried reinstalling the `logiconf-gui` package and nothing. Am i meant to do something with the files in the logiconf folder in my home directory?

**Comment by dslul** [comment]
Well this is strange. The config file is generated automatically and should not require user intervention. Can you post the content of this file?

**Comment by Novantric** [comment]
[logiconf.pro.gz](https://github.com/dslul/logiconf/files/3494330/logiconf.pro.gz)
The logiconf.pro file at the root of the logiconf directory?

Like in the question name, I don't believe it to be my fault but the codes'. I expect you've not updated it for a while. I'm running Linux Mint 19.02 btw.

**Comment by Novantric** [comment]
Any chance you could send a .zip with all the program files in the logiconf folder from a working install? Maybe even the files from other folders as well would be logical, and Including the logiconf-gui package just in case.

**Comment by dslul** [comment]
I don't have my PC with me right now (I'm on vacation), but as soon as I return home I'll try to find a solution

**Comment by dslul** [comment]
@NovaStorm64 can you try this version and see if it works? 

[logiconf-gui.zip](https://github.com/dslul/logiconf/files/3515261/logiconf-gui.zip)

**Comment by Novantric** [comment]
Same issue, and on a different computer as well.
Sorry

**Comment by dslul** [comment]
Can you post the content of this file?
`cat $HOME/.local/share/logiconf-gui/settings.json` 

Also try putting this one (uncompressed) from my computer
[settings.json.zip](https://github.com/dslul/logiconf/files/3537542/settings.json.zip)

**Comment by Novantric** [comment]
[Files.zip](https://github.com/dslul/logiconf/files/3538038/Files.zip)

**Comment by Novantric** [comment]
Nien. Still not working even with the updated executable you sent earlier.
still
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted

**Comment by dslul** [comment]
I can try to reproduce this problem on a clean install. What's your operating system?

**Comment by Novantric** [comment]
Ubuntu 18.04

**Comment by dslul** [comment]
@NovaStorm64 I think they changed something in the mouse, because I couldn't reproduce your problem in a fresh install. The program shouldn't fail though, so there is definitely a problem.

Here are some tools I use for debugging (from libhidpp):
[hidpp-tools.zip](https://github.com/dslul/logiconf/files/3940340/hidpp-tools.zip)

Do you mind posting the results of the following commands?

```
./hidpp-list-devices
hid_path=`./hidpp-list-devices | cut -f1 -d" "|cut -f1 -d":"`
./hidpp-check-device $hid_path
./hidpp-list-features $hid_path
./hidpp20-onboard-profiles-get-description $hid_path
./hidpp20-dump-page $hid_path 0|xxd
./hidpp20-dump-page $hid_path 1|xxd
./hidpp20-dump-page $hid_path 2|xxd
```

**Comment by dslul** [comment]
@NovaStorm64 I think I found the culprit, there was this other [issue](https://github.com/dslul/logiconf/issues/4) with a problem like this. I think you have different shared libraries, so I built a self-contained AppImage that contains all the program needs. You can download it from the release tab ([direct link here](https://github.com/dslul/logiconf/releases/download/0.2.1/logiconf-x86_64.AppImage)).

**Comment by Novantric** [comment]
That's great! Sorry I didn't reply, I mainly forgot and I switched to using G Suite on windows as I use my pc for game performance. 
But I am glad you've found a solution! Next time I use Linux I'll make sure to download it.
Glad I could help!

**Comment by bi0tech** [comment]
Having the same issue with the AppImage, G402 using Manjaro 5.4.24 kernel

> /dev/hidraw3
> angle_snapping
> color
> default_dpi
> name
> report_rate
> revision
> switched_dpi
> terminate called after throwing an instance of 'std::out_of_range'
>   what():  map::at
> Aborted (core dumped)

All 3 profiles are blank (0xff)

---

edit:  Had enough time to setup a windows vm and use the logitech gaming software which apparently populates some of the first two profile pages.   After that the program seems to launch without issue from the appimage.
